### ISSUE TITLE
Archlinux 64 bit

### ISSUE THREAD

**Issue by acidjunk** [ThiefMaster/maildump#3]
When I start maildump:
No PID file specified; runnning in foreground
[2014-08-25 20:51:03]  NOTICE    maildump: Starting web server on http://0.0.0.0:1080
[2014-08-25 20:51:03]  NOTICE    maildump: Starting smtp server on 0.0.0.0:1025
[2014-08-25 20:51:03]  INFO      maildump.db: Using database :memory:
Traceback (most recent call last):
  File "core.pyx", line 337, in gevent.core.__simple_handler (gevent/core.c:5130)
SystemError: NULL result without error in PyObject_Call
Failed to execute callback for active_event fd=-1 flags=INIT
  cb  = <built-in method switch of Greenlet object at 0x7f3c9c5a1050>
  arg = ((), { })

Traceback (most recent call last):
  File "core.pyx", line 337, in gevent.core.__simple_handler (gevent/core.c:5130)
  File "/usr/lib/python2.7/site-packages/gevent/event.py", line 105, in _notify_links
    assert getcurrent() is get_hub()
AssertionError
Failed to execute callback for active_event fd=-1 flags=INIT
  cb  = <bound method Event._notify_links of <gevent.event.Event object at 0x7f3c9c590950>>
  arg = (([<built-in method switch of Greenlet object at 0x7f3c9c5a1050>],), { })

Segmentation fault (core dumped)

I installed libevent with package manager rest of the stuff via easy_install with python 2.7.
Am I missing some deps?

**Comment by ThiefMaster** [comment]
Most likely obsolete.
