### ISSUE TITLE
Installation section in README

### ISSUE THREAD

**Issue by dokteurstore** [ThiefMaster/maildump#33]
Since there is no installation procedure in the README, I've tried to install maildump in this way :
1. Downloaded source code from v1.0
2. Extracted it
3. executed `python3 setup.py build`
4. executed `python3 setup.py install`
5. Launched server with `maildump`

And I get an **Internal Server Error** when trying to connect to [http://127.0.0.1:1080](http://127.0.0.1:1080)

Here is the trace : 
```bash
[2021-01-19 12:21:48,336] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/Flask-1.1.2-py3.8.egg/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/Flask-1.1.2-py3.8.egg/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/Flask-1.1.2-py3.8.egg/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/Flask-1.1.2-py3.8.egg/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/Flask-1.1.2-py3.8.egg/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/Flask-1.1.2-py3.8.egg/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/maildump-1.0-py3.8.egg/maildump/web.py", line 39, in home
    return render_template('index.parcel.html', version=get_version())
  File "/usr/local/lib/python3.8/dist-packages/Flask-1.1.2-py3.8.egg/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.8/dist-packages/Jinja2-3.0.0a1-py3.8.egg/jinja2/environment.py", line 885, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.8/dist-packages/Jinja2-3.0.0a1-py3.8.egg/jinja2/environment.py", line 838, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.8/dist-packages/Jinja2-3.0.0a1-py3.8.egg/jinja2/environment.py", line 812, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.8/dist-packages/Jinja2-3.0.0a1-py3.8.egg/jinja2/loaders.py", line 112, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.8/dist-packages/Flask-1.1.2-py3.8.egg/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.8/dist-packages/Flask-1.1.2-py3.8.egg/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.parcel.html
```

So can anyone update the Documenattion to make the installation process more clear ? Thanks

**Comment by dokteurstore** [comment]
Fixed it.
So I shouldn't have installed it from source
just `pip3 install maildump`

**Comment by ThiefMaster** [comment]
You are right, maildump should be installed using `pip`.

When building from source for whatever reason, you would need to use `npm ci` and `npm run build` to build the webapp frontend.
